#!/bin/bash
#
# i3_keymap_toggle.sh
# Copyright (C) 2016 czystek <czystek@undefined>
#
# Distributed under terms of the MIT license.
#

LG=$(setxkbmap -query | awk '/layout/{print $2}') 

if [[ "pl" = "$LG" ]]
then
  setxkbmap hu
elif [[ "hu" = "$LG" ]]
then
  setxkbmap pl
fi
